Igorosipov/wid 97 discord bot multitenancy
worldcoin/world-id-discord-bot pull request #10
Opened 2022-09-11 13:25 UTC by igorosip0v

### Changes:

## landing-page

- Make `Install Now` and `Add to Discord` buttons lead to discord auth page, after successful auth it redirects to `/auth` page which gets token from query params and fetches guilds list from discord API, then passes it and redirect to `/configuration` page.
- Add "Server" field in configuration form with list of guilds where user have Administrator status.
- Add saving config to DynamoDB.

### Require improvements: 
 - Some data (such as dynamoDB table name, aws creds, discord auth redirect URL) stored in `.env.local` file. May be there is better way to get/store this data.

### How to create discord auth URL:
- Go to [Discord developer portal](https://discord.com/developers).
- Click `New application`
- Go to OAuth2 section -> General.
- Add redirect to a proper url. In my case I've set `https://localhost:3000/auth`
- Go to OAuth2 -> URL Generator
- Set `identity` and `guilds` checkboxes
- Set your saved redirect url
- Get your generated URL
- In generated URL change search param `response_type` value from `code` to `token`. (response_type=token)

## bot updates

- Update context values
    - Remove `action_id`
    - Remove `roles`
    - Add `bot_configs_table_name`
- Create new DynamoDB table with name from context value.
  - Primary key: `guild_id`: string
  - `action_id` field: string
  - `roles` field: list of strings
- Add readonly permissions to configure lambda, verification lambda, role assigning lambda to read values from DynamoDB.
- Fetch data from DynamoDB to create roles, verify with action_id from DB, assign roles.

### Require improvements: 
- Data fetches from DynamoDB three times, when bot adds to server, on verification process, when roles assigned. I assume there is the way to fetch it once and share it in code, but I'm not sure how to share some data between lambdas.

---
<details>
<summary>🎥 Screencast</summary>

https://user-images.githubusercontent.com/89008845/189528632-658cad92-b15d-42ca-9fb9-0ee8e7cc5858.mp4
</details>

2022-09-12 12:22 UTC, igorosip0v commented on src/landing-page/src/screens/Configuration/index.tsx
> +                rel="noopener noreferrer"
@paolodamico eslint fixes it on save. 

eslint([react/jsx-no-target-blank](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/jsx-no-target-blank.md))

2022-09-12 12:38 UTC, igorosip0v commented on src/landing-page/src/screens/Configuration/index.tsx
> +                inputPlaceholder="Enter role name"
@paolodamico This is not a search. This input allows user to add custom named role to the list and then pick it from the list to use it on the server. You can see how it works on screencast.

2022-09-12 12:39 UTC, igorosip0v commented on src/landing-page/src/screens/Configuration/index.tsx
> +  { label: "Moderator", value: "Moderator" },
@paolodamico Some default role names, so that the user can select them at once

2022-09-13 15:20 UTC, igorosip0v commented on src/world-id/resources.queue-processing.ts
> +    console.log(error);
@paolodamico updated

2022-09-13 15:21 UTC, igorosip0v commented on src/world-id/resources.queue-processing.ts
> +    console.log(`Starting verification with action_id: ${action_id}`);
@paolodamico Let's make a separate task for this. What do you think?

2022-09-14 11:31 UTC, gvidon requested changes
@ottodimi please feel free requesting a review on top of my feedback.

2022-09-14 11:31 UTC, gvidon commented on src/landing-page/src/screens/Auth/index.tsx
> +  return await fetch("https://discord.com/api/users/@me/guilds", {
@igorosip0v just curious, do they have SDK lib for Discord?

2022-09-14 11:31 UTC, gvidon commented on src/utils/get-bot-config.ts
> +  } catch (error) {
@igorosip0v just to avoid nested blocks of code let's only wrap the `client.send()` with try/catch.

2022-09-14 11:31 UTC, gvidon commented on src/utils/get-bot-config.ts
> +export const getBotConfig = async (guild_id: string) => {
@igorosip0v can we explicitly assign a type for the function return value?

2022-09-14 11:31 UTC, gvidon commented on src/world-id/assign-roles-on-verified.lambda.ts
> +  const ROLES_TO_ASSIGN = guildBotConfig.data.roles;
@igorosip0v why is it in a cap case?

2022-09-14 11:31 UTC, gvidon commented on src/landing-page/src/utils/save-bot-config.ts
> +const TABLE_NAME = process.env.REACT_APP_AWS_DYNAMODB_TABLE_NAME;
@paolodamico @igorosip0v it should be passed from the DB stack down to the landing page stack. But I'm not sure if the landing page already has a stack defined. It's probably not yet deployed anywhere?

2022-09-14 11:31 UTC, gvidon commented on src/utils/get-bot-config.ts
> +type BotConfig = {
@igorosip0v the type repeats the one defined above. Do you think we can move it to common location in the code?

2022-09-14 11:31 UTC, gvidon commented on src/landing-page/src/utils/dynamodb-client.ts
> +export const client = new DynamoDBClient({
@paolodamico that's correct, we can generate creds in the DB stack, and then pass to landing page stack. But I'm not sure how is the landing page currently deployed.

2022-09-14 11:50 UTC, ottodimi commented on src/world-id/resources.ts
> +      tableName: string;
If you are not provisioning table then take `table: ITable` as parameter (similarly to `botToken: ISecret`).

2022-09-14 11:52 UTC, ottodimi commented on src/world-id/resources.ts
> +    rolesAssigningLambda.role?.addManagedPolicy(dynamodbManagedReadonlyPolicy);
Once you have `table: ITable` use `table.grantRead(rolesAssigningLambda)` instead of granting read only access to all tables in account.

2022-09-14 12:11 UTC, ottodimi requested changes

2022-09-14 12:11 UTC, ottodimi commented on src/world-id/assign-roles-on-verified.lambda.ts
> +  const ROLES_TO_ASSIGN = guildBotConfig.data.roles;
Uppercase is confusing because value is no longer passed through environment variable.

2022-09-14 12:11 UTC, ottodimi commented on src/bot.stack.ts
> +      console.log(error);
You can't just log error and leave `TABLE_NAME` as empty string.

2022-09-14 12:16 UTC, igorosip0v commented on src/bot.stack.ts
> +        scope.node.tryGetContext("bot_configs_table_name") as string,
@gvidon It's the only place where we use this context value. Is it acceptable to just hardcode the table name, or what are the other options?

2022-09-14 12:49 UTC, gvidon commented on src/bot.stack.ts
> +        scope.node.tryGetContext("bot_configs_table_name") as string,
@igorosip0v if this is the only place — yeah, let's simply hardcode it. All the consumers of the table within CDK stack will take it from the resource.

2022-09-14 13:11 UTC, igorosip0v commented on src/endpoints/oauth2-callback.lambda.ts
> +      body: `Please configure your bot settings first. You can update your configuration here: <Configuration Landing page>`,
@gvidon There should be a production deployed address with the `/auth` route, something like `https://world-id-discord-bot.com/auth`

2022-09-15 09:16 UTC, igorosip0v commented on src/bot.stack.ts
> +          minCapacity: 1,
Updated

2022-09-15 09:16 UTC, igorosip0v commented on src/bot.stack.ts
> +        scope.node.tryGetContext("bot_configs_table_name") as string,
Updated

2022-09-15 09:16 UTC, igorosip0v commented on src/bot.stack.ts
> +      TABLE_NAME = table.tableName;
Updated

2022-09-15 09:16 UTC, igorosip0v commented on src/bot.stack.ts
> +        .scaleOnUtilization({ targetUtilizationPercent: 75 });
Updated

2022-09-15 09:20 UTC, igorosip0v commented on src/utils/get-bot-config.ts
> +  } catch (error) {
Updated

2022-09-15 09:20 UTC, igorosip0v commented on src/utils/get-bot-config.ts
> +export const getBotConfig = async (guild_id: string) => {
Updated

2022-09-15 09:20 UTC, igorosip0v commented on src/world-id/assign-roles-on-verified.lambda.ts
> +  const ROLES_TO_ASSIGN = guildBotConfig.data.roles;
Updated

2022-09-15 09:20 UTC, igorosip0v commented on src/utils/get-bot-config.ts
> +type BotConfig = {
Updated

2022-09-15 09:20 UTC, igorosip0v commented on src/world-id/resources.ts
> +      tableName: string;
Updated

2022-09-15 09:20 UTC, igorosip0v commented on src/world-id/resources.ts
> +    rolesAssigningLambda.role?.addManagedPolicy(dynamodbManagedReadonlyPolicy);
Updated

2022-09-15 09:20 UTC, igorosip0v commented on src/world-id/resources.ts
> +    this.processor.role?.addManagedPolicy(dynamodbManagedReadonlyPolicy);
Updated

2022-09-15 09:20 UTC, igorosip0v commented on src/world-id/assign-roles-on-verified.lambda.ts
> +  const ROLES_TO_ASSIGN = guildBotConfig.data.roles;
Updated

2022-09-15 09:27 UTC, igorosip0v commented on src/bot.stack.ts
> +      console.log(error);
@ottodimi Do we need try/catch around table creation? I thought `dynamodb.Table` would throw an error if the table existed, but it seems like it does nothing when the table exists and there are no changes for this table. And if there are some changes,`dynamodb.Table` will apply it to the existing table. What is the cases when table creation can throw an error?

2022-09-15 11:21 UTC, ottodimi commented on src/landing-page/src/utils/dynamodb-client.ts
> +    sessionToken: process.env.REACT_APP_AWS_SESSION_TOKEN,
Usage of `sessionToken` suggests that these are temporary credentials that are going to expire. In general you don't need to specify credentials explicitly (except few special cases when you know what you are doing), just let aws sdk to discover them automatically.

2022-09-15 13:04 UTC, ottodimi commented on src/bot.stack.ts
> +      console.log(error);
Table is not created inside of `try...catch`, it's way more complicated. These constructs (classes that `extends Construct`) declare what infrastructure will look like and how the pieces are connected together. This hierarchy of constructs is then converted into JSON document during `cdk deploy` or `cdk synth` (can be found inside `cdk.out/` directory). JSON documents subsequently are sent to AWS for provisioning. Provisioning (actual process of creating a table) happens entirely in cloud, you cannot catch anything there. You may even reboot your PC and it's still going to continue.

TL;DR: `try...catch` is useless.

2022-09-16 08:24 UTC, igorosip0v commented on src/bot.stack.ts
> +      console.log(error);
Got it, thanks!

2022-09-16 09:52 UTC, igorosip0v commented on src/landing-page/src/screens/Auth/index.tsx
> +  return await fetch("https://discord.com/api/users/@me/guilds", {
There is some libs, but it's simplier to make a single request this way in my opinion

2022-09-19 14:34 UTC, ottodimi approved these changes

2022-11-11 11:35 UTC, igorosip0v commented
@paolodamico 

I've made a dev branch for a [staging domain](https://staging-wld-id-bot.vercel.app/). It synced with this PR, so you can test updated flow there. Currently staging page working with the bot from the AWS dev account ([configured for staging](https://github.com/worldcoin/world-id-discord-bot/blob/igorosipov/wid-97-discord-bot-multitenancy/src/endpoints/oauth2-callback.lambda.ts#L142)). 

---

https://user-images.githubusercontent.com/89008845/201331849-6719f3a9-8bf8-456f-93fa-fe0ce7b1d293.mp4

2022-11-23 20:00 UTC, gvidon approved these changes
Let's finally merge it!🚀

2022-12-05 17:03 UTC, gvidon commented
Closing this as it seems to be no longer relevant. @paolodamico please feel free to revert if I'm wrong.

2022-12-05 17:03 UTC, closed without merging